export const ABOVE_FOLD_TEXT_SHIMMERS = false;
export const DEBUG_UI = false;

export const TESTIMONIAL_COLLAPSED_MAX_HEIGHT_PX = 420;
export const TESTIMONIAL_DESKTOP_BREAKPOINT_PX = 800;
export const TESTIMONIAL_SPACE_BETWEEN_PX = 24;

export const MOBILE_NAV_BREAKPOINT_PX = 900;
